__title__ = "PyGrassClient"
__description__ = "Get Grass Python Package"
__url__ = "https://github.com/Confusion-ymc/PyGrassClient"
__version__ = "2.0.2"
__author__ = "confusion"
__author_email__ = "1107238486@qq.com"
__license__ = "Apache-2.0"